on:
  push:
    branches:
      - Course-Homepage
  workflow_dispatch:

name: Render and Publish Quarto Site

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Configure git identity
        run: |
          git config --global user.name "Quarto GHA Workflow Runner"
          git config --global user.email "quarto-github-actions-publish@example.com"

      - name: Publish to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto publish gh-pages --no-prompt --no-browser
